- hosts: lala
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_network_os: cisco.ios.ios
    CMAS_ADMIN_ADDRESSES:
      - 10.10.10.10
      - 10.10.10.12
      - 10.10.10.13

  tasks:
    - name: Replace ACL for access
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
              - name: CMAS_ADMIN
                acl_type: standard
                aces: >-
                  {{ lookup('template', 'templates/CMAS_ADMIN.yml')
                  | ansible.builtin.from_yaml }}
        state: rendered
